name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Updated to a more recent Node.js version

    - name: Validate package.json
      run: |
        if jq . package.json >/dev/null 2>&1; then
          echo "package.json is valid"
        else
          echo "package.json is invalid"
          exit 1
        fi

    - name: Install dependencies
      run: |
        npm cache clean --force
        rm -rf node_modules package-lock.json
        npm install

    - name: Display npm logs
      if: failure()
      run: cat /home/runner/.npm/_logs/2024-10-12T04_09_01_933Z-debug.log

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
